export const ROMANIAN_CITIES = [
  '2 Mai',
  'Abrud',
  'Adjud',
  'Agnita',
  'Aiud',
  'Alba Iulia',
  'Albac',
  'Aleșd',
  'Alexandria',
  'Amara',
  'Anina',
  'Arad',
  'Arbore',
  'Arefu',
  'Arieșeni',
  'Arpașu de Jos',
  'Avram Iancu',
  'Avrig',
  'Azuga',
  'Bacău',
  'Babadag',
  'Baia de Aramă',
  'Baia de Arieș',
  'Baia Mare',
  'Baia Sprie',
  'Băicoi',
  'Băile 1 Mai',
  'Băile Felix',
  'Băile Herculane',
  'Băile Olănești',
  'Băile Tușnad',
  'Băilești',
  'Bălan',
  'Bălcești',
  'Balș',
  'Baraolt',
  'Bârlad',
  'Bârsana',
  'Bascov',
  'Beclean',
  'Beliș',
  'Beica de Jos',
  'Berești',
  'Bicaz',
  'Biertan',
  'Bilciurești',
  'Bistrița',
  'Blaj',
  'Bocșa',
  'Bogdan Vodă',
  'Boldești-Scăeni',
  'Bolintinul-Morii',
  'Borșa',
  'Borsec',
  'Borzești',
  'Botoșani',
  'Brad',
  'Brăila',
  'Bran',
  'Brașov',
  'Breaza',
  'Brezoi',
  'Broșteni',
  'Bucerdea Grânoasă',
  'București',
  'Budești',
  'Buftea',
  'Buhuși',
  'Buila',
  'Bumbeşti-Jiu',
  'Bumbești-Pițic',
  'Bușteni',
  'Buzău',
  'Buziaș',
  'Cacica',
  'Cajvana',
  'Călărași',
  'Câmpeni',
  'Câmpina',
  'Câmpulung',
  'Câmpulung Moldovenesc',
  'Caracal',
  'Caransebeș',
  'Carei',
  'Cârlibaba',
  'Cârțișoara',
  'Cavnic',
  'Călan',
  'Călimănești',
  'Cernavodă',
  'Cheia',
  'Chiojdeanca',
  'Chișineu-Criș',
  'Chitila',
  'Ciocănești',
  'Cisnădie',
  'Cisnădioara',
  'Cluj-Napoca',
  'Codlea',
  'Comarnic',
  'Comănești',
  'Constanța',
  'Copșa Mică',
  'Corabia',
  'Corbu',
  'Corbeni',
  'Costești',
  'Costinești',
  'Covasna',
  'Cozia',
  'Craiova',
  'Crișan',
  'Crișcior',
  'Cristian',
  'Cristuru Secuiesc',
  'Cula',
  'Curtea de Argeș',
  'Curtici',
  'Dăbuleni',
  'Dărmănești',
  'Darabani',
  'Dej',
  'Densus',
  'Deta',
  'Deva',
  'Dolhasca',
  'Dolj',
  'Dorohoi',
  'Drăgănești-Olt',
  'Drăgășani',
  'Drobeta-Turnu Severin',
  'Dumbrăveni',
  'Eforie Nord',
  'Eforie Sud',
  'Fălticeni',
  'Făgăraș',
  'Făget',
  'Fântânele',
  'Feldioara',
  'Fetești',
  'Fieni',
  'Filiași',
  'Flămânzi',
  'Focșani',
  'Frasin',
  'Fundata',
  'Fundulea',
  'Gârceni',
  'Gârda de Sus',
  'Gătaia',
  'Găești',
  'Geoagiu',
  'Gheorgheni',
  'Gherla',
  'Giurgiu',
  'Glina',
  'Govora',
  'Grădiștea',
  'Grădiștea de Munte',
  'Gura Humorului',
  'Hârlău',
  'Hârșova',
  'Hațeg',
  'Harghita-Băi',
  'Huedin',
  'Humor',
  'Hunedoara',
  'Husi',
  'Iacobeni',
  'Ianca',
  'Iași',
  'Iernut',
  'Ieud',
  'Ilieni',
  'Ineu',
  'Însurăței',
  'Întorsura Buzăului',
  'Isaccea',
  'Izvoru Mureșului',
  'Jibou',
  'Jimbolia',
  'Jupiter',
  'Late',
  'Lăzarea',
  'Lehliu Gară',
  'Lepșa',
  'Lipova',
  'Liteni',
  'Livezi',
  'Lugoj',
  'Lumina',
  'Lupeni',
  'Măcin',
  'Mădăraș',
  'Măgurele',
  'Mahmudia',
  'Măneciu',
  'Mangalia',
  'Marghita',
  'Marginea',
  'Mărișel',
  'Medgidia',
  'Mediaș',
  'Mehadia',
  'Mercurea Sibiului',
  'Meziad',
  'Miercurea Ciuc',
  'Miercurea Nirajului',
  'Mila 23',
  'Mihăilești',
  'Milcov',
  'Mizil',
  'Moeciu de Jos',
  'Moeciu de Sus',
  'Mogoș',
  'Mogoșoaia',
  'Moinești',
  'Moisei',
  'Moldovița',
  'Moreni',
  'Motru',
  'Murfatlar',
  'Murighiol',
  'Nădlac',
  'Năsăud',
  'Năvodari',
  'Negru Vodă',
  'Nehoiu',
  'Neptun',
  'Novaci',
  'Nucet',
  'Ocna Mureș',
  'Ocna Sibiului',
  'Ocnele Mari',
  'Odobeşti',
  'Odorheiu Secuiesc',
  'Oltenița',
  'Oncești',
  'Onești',
  'Oradea',
  'Orăștie',
  'Oravița',
  'Orșova',
  'Otelu Roșu',
  'Otopeni',
  'Ovid',
  'Ozun',
  'Padina',
  'Pâncota',
  'Panciu',
  'Pașcani',
  'Păltiniș',
  'Pătrăuți',
  'Pecica',
  'Peciu Nou',
  'Periam',
  'Peștera',
  'Petrila',
  'Petroșani',
  'Petrova',
  'Piatra Neamț',
  'Piatra-Olt',
  'Ploiești',
  'Poienile Izei',
  'Pojorâta',
  'Popești-Leordeni',
  'Porumbacu',
  'Praid',
  'Predeal',
  'Pucioasa',
  'Putna',
  'Răcari',
  'Răchițele',
  'Rădăuți',
  'Răducăneni',
  'Râmnicu Sărat',
  'Râmnicu Vâlcea',
  'Râșnov',
  'Rarău',
  'Recaș',
  'Reghin',
  'Remetea',
  'Remetea Mare',
  'Reșița',
  'Rimetea',
  'Roman',
  'Roșiorii de Vede',
  'Rozavlea',
  'Rucăr',
  'Rupea',
  'Rușchița',
  'Sâcel',
  'Săcele',
  'Săcueni',
  'Sadova',
  'Salonta',
  'Sălaj',
  'Sângeorgiu de Pădure',
  'Sânnicolau Mare',
  'Sântana',
  'Săpânța',
  'Sarmizegetusa',
  'Saturn',
  'Săveni',
  'Scărișoara',
  'Sebeș',
  'Sebiș',
  'Segarcea',
  'Seini',
  'Sfântu Gheorghe',
  'Sfântu Gheorghe (Delta)',
  'Shimian',
  'Sibiu',
  'Sighetu Marmației',
  'Sighișoara',
  'Simeria',
  'Simon',
  'Sinaia',
  'Șimleu Silvaniei',
  'Șiret',
  'Șirnea',
  'Slănic',
  'Slănic-Moldova',
  'Slobozia',
  'Solca',
  'Șomcuta Mare',
  'Sovata',
  'Ștefan cel Mare',
  'Ștefănești',
  'Ștei',
  'Stâna de Vale',
  'Strehaia',
  'Strâmtura',
  'Suceava',
  'Sucevița',
  'Sulina',
  'Suseni',
  'Șiria',
  'Tălmaciu',
  'Târgoviște',
  'Târgu Bujor',
  'Târgu Cărbunești',
  'Târgu Frumos',
  'Târgu Jiu',
  'Târgu Lăpuș',
  'Târgu Mureș',
  'Târgu Neamț',
  'Târgu Ocna',
  'Târgu Secuiesc',
  'Târnăveni',
  'Tășnad',
  'Țebea',
  'Techirghiol',
  'Tecuci',
  'Teiuș',
  'Timișoara',
  'Tismana',
  'Toplița',
  'Topoloveni',
  'Tulcea',
  'Turceni',
  'Turda',
  'Turnu Măgurele',
  'Turnu Roșu',
  'Tușnad',
  'Ulmeni',
  'Ungheni',
  'Uricani',
  'Urlați',
  'Urziceni',
  'Vadul Crișului',
  'Valea Viilor',
  'Valea lui Mihai',
  'Vălenii de Munte',
  'Vama',
  'Vânju Mare',
  'Vârful Câmpului',
  'Vașcău',
  'Vatra Dornei',
  'Vaslui',
  'Venus',
  'Vețel',
  'Victoria',
  'Videle',
  'Vidra',
  'Vidraru',
  'Vișeu de Jos',
  'Vișeu de Sus',
  'Viscri',
  'Vlăhița',
  'Voineasa',
  'Voluntari',
  'Voroneț',
  'Vulcan',
  'Zahorna',
  'Zalău',
  'Zărnești',
  'Zimnicea',
];
